// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	context "context"
	models "tender/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// RollbackService is an autogenerated mock type for the RollbackService type
type RollbackService struct {
	mock.Mock
}

// SaveBid provides a mock function with given fields: ctx, _a1
func (_m *RollbackService) SaveBid(ctx context.Context, _a1 models.Bid) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveBid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Bid) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SwapBid provides a mock function with given fields: ctx, bidId, version, outdatedBid
func (_m *RollbackService) SwapBid(ctx context.Context, bidId uuid.UUID, version int32, outdatedBid models.Bid) (models.Bid, error) {
	ret := _m.Called(ctx, bidId, version, outdatedBid)

	if len(ret) == 0 {
		panic("no return value specified for SwapBid")
	}

	var r0 models.Bid
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, models.Bid) (models.Bid, error)); ok {
		return rf(ctx, bidId, version, outdatedBid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int32, models.Bid) models.Bid); ok {
		r0 = rf(ctx, bidId, version, outdatedBid)
	} else {
		r0 = ret.Get(0).(models.Bid)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int32, models.Bid) error); ok {
		r1 = rf(ctx, bidId, version, outdatedBid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRollbackService creates a new instance of RollbackService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRollbackService(t interface {
	mock.TestingT
	Cleanup(func())
}) *RollbackService {
	mock := &RollbackService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
