// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	context "context"
	models "tender/internal/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// TenderService is an autogenerated mock type for the TenderService type
type TenderService struct {
	mock.Mock
}

// Tender provides a mock function with given fields: ctx, id
func (_m *TenderService) Tender(ctx context.Context, id uuid.UUID) (models.Tender, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Tender")
	}

	var r0 models.Tender
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Tender, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Tender); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Tender)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTenderService creates a new instance of TenderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTenderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TenderService {
	mock := &TenderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
